### ISSUE TITLE
Epic Issue to Explore Next Phase of Credential Status Manager

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/credential-status-manager-git#22]
Using git has served very useful in many use cases but we're finding that we're hitting some limitations. For instance, the git api may change without notice and there may be limits on requests.

This issue is to explore the next phase of how DCC will suggest management of credential status.

**Comment by kezike** [comment]
## Credential Status Manager Update

### Motivation
Last year, we decided to implement a Git-based credential status manager that implements [Status List 2021](https://www.w3.org/TR/vc-status-list) and hosts credential status resources in Git services. To date, we have an implementation for GitHub and GitLab that perform the basic operations of credential status verification with additional measures for fault tolerance necessary for production deployment. However, it has been brought to our attention at DCC that some of our clients may have reservations about a system with this design, largely due to limitations with Git service APIs. For these clients, we require an alternative solution.

### Proposal
In order to address the foregoing concerns, we need to implement a credential status manager that uses a hosting/storage API that is more reliable and fault tolerant than Git service APIs. This service needs to be able to accommodate several concurrent authenticated requests and host a gradually growing event log. The methods of the new service client should utilize the same general interface as the Git service clients with the new API service.

### Requirements
* Admissible services must support accessing resources via a URL in order to expose Status List 2021 credentials
* Admissible services must be able to accommodate several concurrent authenticated requests
* Admissible services must be able to host a gradually growing event log

### Decisions
* Which API should we use to manage credential status resources?
    * Amazon S3 API
    * Google Cloud Storage API
    * Microsoft Azure Blob Storage API
    * DigitalOcean Spaces API
    * Firebase Storage API
    * MinIO API (can be used to create private cloud storage; compatible with Amazon S3)
    * Backblaze B2 Cloud Storage API
    * Dropbox API
    * Box API
    * OneDrive API
* Where should we implement this new service?
    * Create a separate repo for this new storage API service
    * Remove `-git` from the current repo name add add an additional implementation of the abstract `BaseCredentialStatusManager` class that uses the new storage API service for read/write operations

### Risks
* ???

**Comment by kayaelle** [comment]
New issue: https://github.com/digitalcredentials/credential-status-manager-db
